# meshing settings
mesh:
  size_factor: 1  # use this to change mesh size globally
  order: 1  # 2nd order is better if you want to evaluate heat fluxes

# geometry parameters
base_plate:
  r: 0.165
  t: 0.01
  mesh_size: 0.01
  material: steel

insulation_bot:
  r: 0.1
  h: 0.12
  y0: 0.002
  mesh_size: 0.01
  material: insulation

crucible:
  t_bot: 0.03
  angle: 120  # deg, opening angle of cone at crucible bottom
  r_in: 0.075
  r_out: 0.1
  h: 0.328
  mesh_size: 0.005
  material: graphite
  T_init: 1000  # guessed temperature

crystal:
  h: 0.2
  mesh_size: 0.005
  material: GaAs_solid
  T_init: 1000

melt:
  h: 0.25  # height of melt in crucible, measured from crucible bottom
  mesh_size: 0.005
  material: GaAs_liquid
  T_init: 1000

enclosure:
  r_in: 0.102
  h_in: 0.5
  t: 0.002
  mesh_size: 0.001
  material: steel

heater_side_bot:
  r_in: 0.107
  dy: 0.15
  dx: 0.004
  y0: 0.047
  mesh_size: 0.005
  material: graphite
  T_init: 1000

heater_side_mid:
  r_in: 0.107
  dy: 0.15
  dx: 0.004
  y0: 0.201
  mesh_size: 0.005
  material: graphite
  T_init: 1000

heater_side_top:
  r_in: 0.107
  dy: 0.15
  dx: 0.004
  y0: 0.355
  mesh_size: 0.005
  material: graphite
  T_init: 1000

heater_top:
  r_in: 0.0
  dx: 0.1
  dy: 0.004
  y0: 0.507
  mesh_size: 0.005
  material: graphite
  T_init: 1000

insulation:
  r_in: 0.113
  h_in: 0.513
  t: 0.052
  mesh_size: 0.01
  material: insulation
