# setup for Elmer simulation / solvers
axisymmetric_steady:
  Max Output Level: 4
  Coordinate System: Axi Symmetric
  Simulation Type: Steady state
  Steady State Max Iterations: 10
  Output File: case.result
  Output Intervals: 0

HeatSolver:
  Equation: Heat Equation
  Procedure: '"HeatSolve" "HeatSolver"'
  Variable: '"Temperature"'
  Variable Dofs: 1
  Calculate Loads: True
  Exec Solver: Always
  Nonlinear System Convergence Tolerance: 1.0e-6
  Nonlinear System Max Iterations: 1000
  Nonlinear System Relaxation Factor: 0.7
  Steady State Convergence Tolerance: 1.0e-6
  Stabilize: True 
  Optimize Bandwidth: True
  Linear System Solver: Iterative  
  Linear System Iterative Method: Idrs
  Linear System Max Iterations: 10000
  Linear System Preconditioning: ILU
  Linear System Precondition Recompute: 1
  Linear System Convergence Tolerance: 1.0e-8
  Linear System Abort Not Converged: True
  Linear System Residual Output: 10
  Smart Heater Control After Tolerance: 1.0e-2
ResultOutputSolver:
  Exec Solver: 'after saving'
  Equation: '"ResultOutput"'
  Procedure: '"ResultOutputSolve" "ResultOutputSolver"'
  VTU Format: True
  Vtu Part collection: True
SteadyPhaseChange:
  Equation: PhaseSurface
  Variable: '"PhaseSurface"'
  Procedure: '"SteadyPhaseChange" "SteadyPhaseChange"'
  Triple Point Fixed: Logical True
  Linear System Iterative Method: Idrs
  # Internal Mesh Movement: Logical True
MeshUpdate:
  Equation: Mesh Update
  Linear System Solver: Iterative
  Linear System Iterative Method: BiCGStab
  Linear System Preconditioning: ILU1
  Linear System Max Iterations: 10000
  Linear System Convergence Tolerance: 1e-09
  Linear System Residual Output: 1
  Steady State Convergence Tolerance: 1e-06
