# material parameters for elmer simulation
insulation:
  Density: 220.0
  Emissivity: 0.7
  Heat Conductivity: 0.2
GaAs_solid:
  Density: 7179.0
  Emissivity: 0.064
  Heat Conductivity: 60.0
  Solid: 'Logical True'
  Melting Point: 505
  Latent Heat: 5.96e+4  # J / kg
GaAs_liquid:
  Density: 6980.0
  Emissivity: 0.064
  Heat Conductivity: 29.0
  Liquid: 'Logical True'
steel:
  Density: 7900.0
  Emissivity: 0.2
  Heat Conductivity: 15.0
graphite:
  Density: 1750.0
  Emissivity: 0.81
  Heat Conductivity: 105
