# material parameters for elmer simulation
insulation:
  Density: 220.0
  Emissivity: 0.7
  Heat Conductivity: 0.2
GaAs_solid:
  Density: 5170.0
  Emissivity: 0.55
  Heat Conductivity: 7.12
  Solid: 'Logical True'
  Melting Point: 1511
  Latent Heat: 7.26e+5  # J / kg
GaAs_liquid:
  Density: 5720.0
  Emissivity: 0.55
  Heat Conductivity: 17.8
  Liquid: 'Logical True'
steel:
  Density: 7900.0
  Emissivity: 0.2
  Heat Conductivity: 15.0
graphite:
  Density: 1750.0
  Emissivity: 0.81
  Heat Conductivity: 105
